### PR TITLE
[Close #53] Fix rails app configuration

### LINKED ISSUE #53: Fix rails app configuration
- Set timezone
- Update Rails version to 6.0.3

### PR DESCRIPTION
**Pull request by ayumitamai97**

### CODE REVIEW

File: spec/rails_helper.rb [hunk 1]
```diff
@@ -67,10 +67,12 @@
...
-  config.around(:all) do |example|
+  config.before(:suite) do
     Elasticsearch::CreateIndicesService.new.execute
     sleep 3
-    example.run
+  end
+
+  config.after(:suite) do
     Elasticsearch::DeleteIndicesService.new.execute
   end
```
Comment (ayumitamai97) [inline spec/rails_helper.rb:77]: `around(:suite)` is not supported...
